// Mocks generated by Mockito 5.4.4 from annotations
// in voltwatch/test/presentation/repositories/battery_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:battery_plus/battery_plus.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i3;
import 'package:voltwatch/core/services/settings_service.dart' as _i8;
import 'package:voltwatch/data/datasources/battery_local_datasource.dart'
    as _i2;
import 'package:voltwatch/data/models/battery_log.dart' as _i7;
import 'package:voltwatch/data/repositories/battery_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBatteryLocalDatasource_0 extends _i1.SmartFake
    implements _i2.BatteryLocalDatasource {
  _FakeBatteryLocalDatasource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BatteryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBatteryRepository extends _i1.Mock implements _i4.BatteryRepository {
  MockBatteryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BatteryLocalDatasource get datasource => (super.noSuchMethod(
        Invocation.getter(#datasource),
        returnValue: _FakeBatteryLocalDatasource_0(
          this,
          Invocation.getter(#datasource),
        ),
      ) as _i2.BatteryLocalDatasource);

  @override
  _i5.Future<int> get batteryLevel => (super.noSuchMethod(
        Invocation.getter(#batteryLevel),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i6.BatteryState> get batteryState => (super.noSuchMethod(
        Invocation.getter(#batteryState),
        returnValue: _i5.Future<_i6.BatteryState>.value(_i6.BatteryState.full),
      ) as _i5.Future<_i6.BatteryState>);

  @override
  _i5.Future<bool> get isInBatterySaveMode => (super.noSuchMethod(
        Invocation.getter(#isInBatterySaveMode),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Stream<_i6.BatteryState> get onBatteryStateChanged => (super.noSuchMethod(
        Invocation.getter(#onBatteryStateChanged),
        returnValue: _i5.Stream<_i6.BatteryState>.empty(),
      ) as _i5.Stream<_i6.BatteryState>);

  @override
  _i5.Future<void> saveCurrentBattery() => (super.noSuchMethod(
        Invocation.method(
          #saveCurrentBattery,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i7.BatteryLog> getHistory() => (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [],
        ),
        returnValue: <_i7.BatteryLog>[],
      ) as List<_i7.BatteryLog>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i8.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_1(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i3.SharedPreferences);

  @override
  _i5.Future<void> saveThreshold(int? value) => (super.noSuchMethod(
        Invocation.method(
          #saveThreshold,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getThreshold() => (super.noSuchMethod(
        Invocation.method(
          #getThreshold,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> setTriggered(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setTriggered,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> wasTriggered() => (super.noSuchMethod(
        Invocation.method(
          #wasTriggered,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
