// Mocks generated by Mockito 5.4.4 from annotations
// in voltwatch/test/core/services/battery_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:battery_plus/battery_plus.dart' as _i2;
import 'package:battery_plus_platform_interface/battery_plus_platform_interface.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Battery].
///
/// See the documentation for Mockito's code generation for more information.
class MockBattery extends _i1.Mock implements _i2.Battery {
  MockBattery() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> get batteryLevel => (super.noSuchMethod(
        Invocation.getter(#batteryLevel),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> get isInBatterySaveMode => (super.noSuchMethod(
        Invocation.getter(#isInBatterySaveMode),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i4.BatteryState> get batteryState => (super.noSuchMethod(
        Invocation.getter(#batteryState),
        returnValue: _i3.Future<_i4.BatteryState>.value(_i4.BatteryState.full),
      ) as _i3.Future<_i4.BatteryState>);

  @override
  _i3.Stream<_i4.BatteryState> get onBatteryStateChanged => (super.noSuchMethod(
        Invocation.getter(#onBatteryStateChanged),
        returnValue: _i3.Stream<_i4.BatteryState>.empty(),
      ) as _i3.Stream<_i4.BatteryState>);
}
